package com.joyful.joyfulkitchen.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.joyful.joyfulkitchen.model.Food;
import com.joyful.joyfulkitchen.model.FoodType;
import com.joyful.joyfulkitchen.model.Record;
import com.joyful.joyfulkitchen.model.User;

import com.joyful.joyfulkitchen.dao.FoodDao;
import com.joyful.joyfulkitchen.dao.FoodTypeDao;
import com.joyful.joyfulkitchen.dao.RecordDao;
import com.joyful.joyfulkitchen.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodDaoConfig;
    private final DaoConfig foodTypeDaoConfig;
    private final DaoConfig recordDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FoodDao foodDao;
    private final FoodTypeDao foodTypeDao;
    private final RecordDao recordDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodDaoConfig = daoConfigMap.get(FoodDao.class).clone();
        foodDaoConfig.initIdentityScope(type);

        foodTypeDaoConfig = daoConfigMap.get(FoodTypeDao.class).clone();
        foodTypeDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        foodDao = new FoodDao(foodDaoConfig, this);
        foodTypeDao = new FoodTypeDao(foodTypeDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Food.class, foodDao);
        registerDao(FoodType.class, foodTypeDao);
        registerDao(Record.class, recordDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        foodDaoConfig.clearIdentityScope();
        foodTypeDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FoodDao getFoodDao() {
        return foodDao;
    }

    public FoodTypeDao getFoodTypeDao() {
        return foodTypeDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
