package com.joyful.joyfulkitchen.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.joyful.joyfulkitchen.model.Food;
import com.joyful.joyfulkitchen.model.User;

import com.joyful.joyfulkitchen.model.Record;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tb_record".
*/
public class RecordDao extends AbstractDao<Record, Long> {

    public static final String TABLENAME = "tb_record";

    /**
     * Properties of entity Record.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Record_id = new Property(0, Long.class, "record_id", true, "record_id");
        public final static Property TotalWeight = new Property(1, double.class, "totalWeight", false, "total_weight");
        public final static Property TotalEnergy = new Property(2, double.class, "totalEnergy", false, "total_energy");
        public final static Property MeauName = new Property(3, String.class, "meauName", false, "meau_name");
        public final static Property CreateTime = new Property(4, java.util.Date.class, "createTime", false, "create_time");
        public final static Property UpdateTime = new Property(5, java.util.Date.class, "updateTime", false, "update_time");
        public final static Property UserId = new Property(6, Long.class, "userId", false, "user_id");
        public final static Property FoodId = new Property(7, Long.class, "foodId", false, "food_id");
    }

    private DaoSession daoSession;


    public RecordDao(DaoConfig config) {
        super(config);
    }
    
    public RecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tb_record\" (" + //
                "\"record_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: record_id
                "\"total_weight\" REAL NOT NULL ," + // 1: totalWeight
                "\"total_energy\" REAL NOT NULL ," + // 2: totalEnergy
                "\"meau_name\" TEXT," + // 3: meauName
                "\"create_time\" INTEGER," + // 4: createTime
                "\"update_time\" INTEGER," + // 5: updateTime
                "\"user_id\" INTEGER," + // 6: userId
                "\"food_id\" INTEGER);"); // 7: foodId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tb_record\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Record entity) {
        stmt.clearBindings();
 
        Long record_id = entity.getRecord_id();
        if (record_id != null) {
            stmt.bindLong(1, record_id);
        }
        stmt.bindDouble(2, entity.getTotalWeight());
        stmt.bindDouble(3, entity.getTotalEnergy());
 
        String meauName = entity.getMeauName();
        if (meauName != null) {
            stmt.bindString(4, meauName);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(5, createTime.getTime());
        }
 
        java.util.Date updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(6, updateTime.getTime());
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(7, userId);
        }
 
        Long foodId = entity.getFoodId();
        if (foodId != null) {
            stmt.bindLong(8, foodId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Record entity) {
        stmt.clearBindings();
 
        Long record_id = entity.getRecord_id();
        if (record_id != null) {
            stmt.bindLong(1, record_id);
        }
        stmt.bindDouble(2, entity.getTotalWeight());
        stmt.bindDouble(3, entity.getTotalEnergy());
 
        String meauName = entity.getMeauName();
        if (meauName != null) {
            stmt.bindString(4, meauName);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(5, createTime.getTime());
        }
 
        java.util.Date updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(6, updateTime.getTime());
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(7, userId);
        }
 
        Long foodId = entity.getFoodId();
        if (foodId != null) {
            stmt.bindLong(8, foodId);
        }
    }

    @Override
    protected final void attachEntity(Record entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Record readEntity(Cursor cursor, int offset) {
        Record entity = new Record( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // record_id
            cursor.getDouble(offset + 1), // totalWeight
            cursor.getDouble(offset + 2), // totalEnergy
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // meauName
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // createTime
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // updateTime
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // userId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // foodId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Record entity, int offset) {
        entity.setRecord_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTotalWeight(cursor.getDouble(offset + 1));
        entity.setTotalEnergy(cursor.getDouble(offset + 2));
        entity.setMeauName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreateTime(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setUpdateTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setUserId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setFoodId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Record entity, long rowId) {
        entity.setRecord_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Record entity) {
        if(entity != null) {
            return entity.getRecord_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Record entity) {
        return entity.getRecord_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getFoodDao().getAllColumns());
            builder.append(" FROM tb_record T");
            builder.append(" LEFT JOIN tb_user T0 ON T.\"user_id\"=T0.\"user_id\"");
            builder.append(" LEFT JOIN tb_food T1 ON T.\"food_id\"=T1.\"food_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Record loadCurrentDeep(Cursor cursor, boolean lock) {
        Record entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);
        offset += daoSession.getUserDao().getAllColumns().length;

        Food food = loadCurrentOther(daoSession.getFoodDao(), cursor, offset);
        entity.setFood(food);

        return entity;    
    }

    public Record loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Record> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Record> list = new ArrayList<Record>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Record> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Record> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
